### ISSUE TITLE
Quality loss

### ISSUE THREAD

**Issue by loredev10** [eworm-de/xcur2png#1]
There is a noticeable loss of quality when extracting images with xcur2png compared to opening them and exporting in Gimp.

I added an example image. On the left is Gimp, on the right is an exported image.

![pointer1](https://user-images.githubusercontent.com/13369896/42124319-03c39bd2-7c69-11e8-92f7-e861319d24f3.png)

**Comment by eworm-de** [comment]
This is just a copy of the source to archive it. I will not care to close bugs.

**Comment by loredev10** [comment]
Where's the original repo?

**Comment by eworm-de** [comment]
The only commit f582d648f37a9ed2de0c8650947487af8a54d3ad has all the details.

**Comment by OdinVex** [comment]
> There is a noticeable loss of quality when extracting images with xcur2png compared to opening them and exporting in Gimp.
> 
> I added an example image. On the left is Gimp, on the right is an exported image.
> 
> ![pointer1](https://user-images.githubusercontent.com/13369896/42124319-03c39bd2-7c69-11e8-92f7-e861319d24f3.png)

It is due to a math issue assuming 256 instead of 255. Bug fix below:

    red = (div (red * 255, alpha).quot) & 0xff;
    green = (div (green * 255,  alpha).quot) & 0xff;
    blue = (div (blue * 255, alpha).quot) & 0xff;

**Comment by eworm-de** [comment]
Thanks for investigating... Pushed this in aa035462d950fab35d322cb87fd2f0d702251e82 to a new branch.

**Comment by OdinVex** [comment]
> Thanks for investigating... Pushed this in [aa03546](https://github.com/eworm-de/xcur2png/commit/aa035462d950fab35d322cb87fd2f0d702251e82) to a new branch.

Most welcome. Thank you for considering the code.

Edit: It might not hurt to add a bit of information to the repo page regarding the bug-fix for quality loss. Two people have asked me why their quality was poor despite the fix being pushed, and I mentioned they had to clone the repo and build it to get the latest fix because the repo only contains (for posterity?) the original build as a release.
